
// getall
GET http://localhost:5181/games

###//get by id
GET http://localhost:5181/games/11

###//update
POST  http://localhost:5181/games 
Content-Type: application/json

{
"Name": "super",
"Genre": "platfomer",
"Price": 32.56,
"ReleaseDate": "2023-10-20"
}


###
PUT  http://localhost:5181/games/3
Content-Type: application/json

{
  "name": "Street fighters IV turbo",
  "genre": "Fighting",
  "price": 19.19,
  "releaseDate": "1292-07-07"
}


### delete
DELETE   http://localhost:5181/games/1


### genres
GET  http://localhost:5181/genres
  